<a href="https://colab.research.google.com/github/profteachkids/CHE2064/blob/master/NeuralNetworkPrimer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import torch
import torch.nn as nn
import torchvision as tv
from plotly.subplots import make_subplots
import sklearn

In [54]:
x = torch.linspace(0,10, 25).unsqueeze(1)
y= torch.sin(x)
x_norm = (x-x.mean())/x.std()

In [63]:
y.shape

torch.Size([25, 1])

In [65]:
lr=1e-1

w1=torch.distributions.Normal(0, 1/20**0.5).sample((1,20)).requires_grad_()
b1=torch.zeros((1,20),requires_grad=True)

for i in range(20000):
  o1=torch.tanh(x_norm@w1+b1)
  predict=torch.sum(o1,dim=1)
  loss = torch.mean((predict-y.squeeze())**2)
  if i % 1000 ==0:
    print(i, loss)
  loss.backward()
  with torch.no_grad():
    w1.sub_(lr * w1.grad)
    b1.sub_(lr * b1.grad)
    # w2.sub_(lr * w2.grad)
    # b2.sub_(lr * b2.grad)
    w1.grad=None
    b1.grad=None
    # w2.grad=None
    # b2.grad=None




0 tensor(0.6119, grad_fn=<MeanBackward0>)
1000 tensor(0.0424, grad_fn=<MeanBackward0>)
2000 tensor(0.0301, grad_fn=<MeanBackward0>)
3000 tensor(0.0191, grad_fn=<MeanBackward0>)
4000 tensor(0.0128, grad_fn=<MeanBackward0>)
5000 tensor(0.0092, grad_fn=<MeanBackward0>)
6000 tensor(0.0070, grad_fn=<MeanBackward0>)
7000 tensor(0.0054, grad_fn=<MeanBackward0>)
8000 tensor(0.0042, grad_fn=<MeanBackward0>)
9000 tensor(0.0031, grad_fn=<MeanBackward0>)
10000 tensor(0.0023, grad_fn=<MeanBackward0>)
11000 tensor(0.0017, grad_fn=<MeanBackward0>)
12000 tensor(0.0013, grad_fn=<MeanBackward0>)
13000 tensor(0.0010, grad_fn=<MeanBackward0>)
14000 tensor(0.0008, grad_fn=<MeanBackward0>)
15000 tensor(0.0007, grad_fn=<MeanBackward0>)
16000 tensor(0.0006, grad_fn=<MeanBackward0>)
17000 tensor(0.0005, grad_fn=<MeanBackward0>)
18000 tensor(0.0004, grad_fn=<MeanBackward0>)
19000 tensor(0.0004, grad_fn=<MeanBackward0>)


In [66]:
fig= make_subplots()
fig.add_scatter(x=x.squeeze(),y=y.squeeze(), mode='markers')
fig.add_scatter(x=x.squeeze(), y=predict.detach().numpy(), mode='lines')
fig.update_layout(width=800,height=500)
fig.show()

In [67]:
x = torch.linspace(0,10, 25).unsqueeze(1)
y= torch.sin(x)

x_norm = (x-x.mean())/x.std()

model = nn.Sequential(nn.Linear(1,20),
                      nn.Tanh(),
                      # nn.Linear(20,20),
                      # nn.Tanh(),
                      nn.Linear(20,1))

loss_fn = nn.MSELoss()
optim = torch.optim.Adam(model.parameters())
for i in range(10000):
  loss = loss_fn(model(x_norm), y)
  if i % 1000 == 0:
    print(i, loss)
  optim.zero_grad()
  loss.backward()
  optim.step()


0 tensor(0.4751, grad_fn=<MseLossBackward>)
1000 tensor(0.0303, grad_fn=<MseLossBackward>)
2000 tensor(0.0013, grad_fn=<MseLossBackward>)
3000 tensor(0.0002, grad_fn=<MseLossBackward>)
4000 tensor(2.2858e-05, grad_fn=<MseLossBackward>)
5000 tensor(7.7597e-06, grad_fn=<MseLossBackward>)
6000 tensor(5.8834e-06, grad_fn=<MseLossBackward>)
7000 tensor(4.6004e-06, grad_fn=<MseLossBackward>)
8000 tensor(3.6064e-06, grad_fn=<MseLossBackward>)
9000 tensor(2.9007e-06, grad_fn=<MseLossBackward>)


In [68]:
fig= make_subplots()
fig.add_scatter(x=x.squeeze(),y=y.squeeze(),mode='markers')
fig.add_scatter(x=x.squeeze(), y=model(x_norm).squeeze().detach().numpy(), mode='lines')
fig.update_layout(width=800,height=500)
fig.show()

In [69]:
transforms=tv.transforms.Compose([tv.transforms.ToTensor()])
mnist=tv.datasets.MNIST('./', download=True, transform=transforms)

Extracting ./MNIST/raw/train-images-idx3-ubyte.gz to ./MNIST/raw


Extracting ./MNIST/raw/train-labels-idx1-ubyte.gz to ./MNIST/raw


Extracting ./MNIST/raw/t10k-images-idx3-ubyte.gz to ./MNIST/raw


Extracting ./MNIST/raw/t10k-labels-idx1-ubyte.gz to ./MNIST/raw
Processing...
Done!


/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py:480: UserWarning:

The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)



In [70]:
sampler = torch.utils.data.DataLoader(mnist, batch_size=64, shuffle=True)
data=iter(sampler)
a=next(data)

In [71]:
pic,label = a
print(pic.shape)
print(label.shape)
img=tv.utils.make_grid(pic, pad_value=255)
print(img.shape)

torch.Size([64, 1, 28, 28])
torch.Size([64])
torch.Size([3, 242, 242])


In [72]:
fig = make_subplots()
fig.add_image(z=img.permute([1,2,0])*255, colormodel='rgb')
fig.update_layout(width=500, height=500, margin=dict(l=2,r=2,b=2,t=2), xaxis_visible=False, yaxis_visible=False)

In [73]:
label.reshape(8,8)

tensor([[3, 0, 1, 7, 6, 4, 8, 9],
        [6, 6, 5, 5, 8, 5, 8, 6],
        [5, 4, 2, 5, 2, 2, 1, 1],
        [2, 3, 4, 5, 2, 7, 9, 0],
        [2, 6, 3, 9, 9, 3, 5, 9],
        [8, 4, 0, 6, 3, 7, 2, 4],
        [6, 3, 9, 2, 6, 7, 2, 7],
        [9, 6, 5, 2, 7, 1, 3, 8]])

In [84]:
model = nn.Sequential(nn.Linear(784,20),
                      nn.Tanh(),
                      nn.Linear(20,10),
                      nn.Softmax(dim=0))


In [85]:
loss_fn = nn.CrossEntropyLoss()
optim = torch.optim.Adam(model.parameters())

for i in range(1000):
  optim.zero_grad()
  predict=model(pic.flatten(1))
  loss = loss_fn(predict,label)
  if i % 100 == 0 :
    print(loss)
  loss.backward()
  optim.step()


tensor(2.3029, grad_fn=<NllLossBackward>)
tensor(2.1956, grad_fn=<NllLossBackward>)
tensor(2.1720, grad_fn=<NllLossBackward>)
tensor(2.1676, grad_fn=<NllLossBackward>)
tensor(2.1661, grad_fn=<NllLossBackward>)
tensor(2.1653, grad_fn=<NllLossBackward>)
tensor(2.1648, grad_fn=<NllLossBackward>)
tensor(2.1645, grad_fn=<NllLossBackward>)
tensor(2.1643, grad_fn=<NllLossBackward>)
tensor(2.1642, grad_fn=<NllLossBackward>)


In [86]:
predict_label=torch.argmax(model(pic.flatten(1)),dim=1)

In [87]:
print(predict_label)
print(label)

tensor([3, 0, 1, 7, 6, 4, 8, 9, 6, 6, 5, 5, 8, 5, 8, 6, 5, 4, 2, 5, 2, 2, 1, 1,
        2, 3, 4, 5, 2, 7, 9, 0, 2, 6, 3, 9, 9, 3, 5, 9, 8, 4, 6, 6, 3, 7, 2, 4,
        6, 3, 9, 2, 6, 7, 2, 7, 9, 6, 5, 2, 7, 1, 3, 8])
tensor([3, 0, 1, 7, 6, 4, 8, 9, 6, 6, 5, 5, 8, 5, 8, 6, 5, 4, 2, 5, 2, 2, 1, 1,
        2, 3, 4, 5, 2, 7, 9, 0, 2, 6, 3, 9, 9, 3, 5, 9, 8, 4, 0, 6, 3, 7, 2, 4,
        6, 3, 9, 2, 6, 7, 2, 7, 9, 6, 5, 2, 7, 1, 3, 8])


In [88]:
torch.mean((predict_label==label).float())

tensor(0.9844)