<a href="https://colab.research.google.com/github/profteachkids/CHE2064/blob/master/NeuralNetworkPrimer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [118]:
import torch
import torch.nn as nn
import torchvision as tv
from plotly.subplots import make_subplots
import sklearn

In [285]:
x = torch.linspace(0,10, 25).unsqueeze(0)
y= torch.sin(x)
x_norm = (x-x.mean())/x.std()

In [292]:
lr=1e-1

w1=torch.distributions.Normal(0, 1/20**0.5).sample((20,1)).requires_grad_()
b1=torch.zeros((20,1),requires_grad=True)

for i in range(20000):
  o1=torch.tanh(w1@x_norm+b1)
  o2=torch.tanh(w2@o1+b2)
  predict=torch.sum(o2,dim=0)
  loss = torch.mean((predict-y)**2)
  if i % 1000 ==0:
    print(i, loss)
  loss.backward()
  with torch.no_grad():
    w1.sub_(lr * w1.grad)
    b1.sub_(lr * b1.grad)
    w2.sub_(lr * w2.grad)
    b2.sub_(lr * b2.grad)
    w1.grad=None
    b1.grad=None
    w2.grad=None
    b2.grad=None




0 tensor(2.3959, grad_fn=<MeanBackward0>)
1000 tensor(0.2582, grad_fn=<MeanBackward0>)
2000 tensor(0.0424, grad_fn=<MeanBackward0>)
3000 tensor(0.0245, grad_fn=<MeanBackward0>)
4000 tensor(0.0007, grad_fn=<MeanBackward0>)
5000 tensor(0.0004, grad_fn=<MeanBackward0>)
6000 tensor(0.0003, grad_fn=<MeanBackward0>)
7000 tensor(0.0002, grad_fn=<MeanBackward0>)
8000 tensor(0.0002, grad_fn=<MeanBackward0>)
9000 tensor(0.0002, grad_fn=<MeanBackward0>)
10000 tensor(0.0002, grad_fn=<MeanBackward0>)
11000 tensor(0.0001, grad_fn=<MeanBackward0>)
12000 tensor(0.0001, grad_fn=<MeanBackward0>)
13000 tensor(0.0001, grad_fn=<MeanBackward0>)
14000 tensor(0.0001, grad_fn=<MeanBackward0>)
15000 tensor(9.9307e-05, grad_fn=<MeanBackward0>)
16000 tensor(9.2025e-05, grad_fn=<MeanBackward0>)
17000 tensor(8.5807e-05, grad_fn=<MeanBackward0>)
18000 tensor(8.0481e-05, grad_fn=<MeanBackward0>)
19000 tensor(7.5911e-05, grad_fn=<MeanBackward0>)


In [293]:
fig= make_subplots()
fig.add_scatter(x=x.squeeze(),y=y.squeeze(), mode='markers')
fig.add_scatter(x=x.squeeze(), y=predict.detach().numpy(), mode='lines')
fig.update_layout(width=800,height=500)
fig.show()

In [294]:
x = torch.linspace(0,10, 25).unsqueeze(1)
y= torch.sin(x)

x_norm = (x-x.mean())/x.std()

model = nn.Sequential(nn.Linear(1,20),
                      nn.Tanh(),
                      nn.Linear(20,20),
                      nn.Tanh(),
                      nn.Linear(20,1))

loss_fn = nn.MSELoss()
optim = torch.optim.Adam(model.parameters())
for i in range(10000):
  loss = loss_fn(model(x_norm), y)
  if i % 1000 == 0:
    print(i, loss)
  optim.zero_grad()
  loss.backward()
  optim.step()


0 tensor(0.5341, grad_fn=<MseLossBackward>)
1000 tensor(0.0028, grad_fn=<MseLossBackward>)
2000 tensor(2.4867e-05, grad_fn=<MseLossBackward>)
3000 tensor(4.0695e-06, grad_fn=<MseLossBackward>)
4000 tensor(2.7334e-06, grad_fn=<MseLossBackward>)
5000 tensor(2.1621e-06, grad_fn=<MseLossBackward>)
6000 tensor(1.7136e-06, grad_fn=<MseLossBackward>)
7000 tensor(1.3517e-06, grad_fn=<MseLossBackward>)
8000 tensor(1.1120e-06, grad_fn=<MseLossBackward>)
9000 tensor(1.4091e-06, grad_fn=<MseLossBackward>)


In [295]:
fig= make_subplots()
fig.add_scatter(x=x.squeeze(),y=y.squeeze(),mode='markers')
fig.add_scatter(x=x.squeeze(), y=model(x_norm).squeeze().detach().numpy(), mode='lines')
fig.update_layout(width=800,height=500)
fig.show()

In [3]:
transforms=tv.transforms.Compose([tv.transforms.ToTensor()])
mnist=tv.datasets.MNIST('./', download=True, transform=transforms)

In [5]:
sampler = torch.utils.data.DataLoader(mnist, batch_size=64, shuffle=True)
data=iter(sampler)
a=next(data)

In [6]:
pic,label = a
print(pic.shape)
print(label.shape)
img=tv.utils.make_grid(pic, pad_value=255)
print(img.shape)

torch.Size([64, 1, 28, 28])
torch.Size([64])
torch.Size([3, 242, 242])


In [7]:
fig = make_subplots()
fig.add_image(z=img.permute([1,2,0])*255, colormodel='rgb')
fig.update_layout(width=500, height=500, margin=dict(l=2,r=2,b=2,t=2), xaxis_visible=False, yaxis_visible=False)

In [8]:
label.reshape(8,8)

tensor([[2, 0, 9, 2, 3, 2, 3, 9],
        [7, 7, 7, 3, 3, 0, 2, 3],
        [7, 7, 7, 4, 8, 3, 3, 1],
        [1, 0, 0, 0, 8, 7, 6, 8],
        [6, 7, 9, 1, 4, 2, 5, 1],
        [1, 8, 6, 5, 7, 5, 4, 7],
        [1, 4, 8, 4, 1, 8, 6, 8],
        [0, 7, 2, 2, 4, 3, 5, 0]])

In [26]:
model = nn.Sequential(nn.Linear(784,20),
                      nn.Tanh(),
                      nn.Linear(20,10),
                      nn.Softmax(dim=0))


In [27]:
loss_fn = nn.CrossEntropyLoss()
optim = torch.optim.Adam(model.parameters())

for i in range(1000):
  optim.zero_grad()
  predict=model(pic.flatten(1))
  loss = loss_fn(predict,label)
  if i % 100 == 0 :
    print(loss)
  loss.backward()
  optim.step()


tensor(2.3026, grad_fn=<NllLossBackward>)
tensor(2.1912, grad_fn=<NllLossBackward>)
tensor(2.1707, grad_fn=<NllLossBackward>)
tensor(2.1672, grad_fn=<NllLossBackward>)
tensor(2.1659, grad_fn=<NllLossBackward>)
tensor(2.1652, grad_fn=<NllLossBackward>)
tensor(2.1648, grad_fn=<NllLossBackward>)
tensor(2.1645, grad_fn=<NllLossBackward>)
tensor(2.1643, grad_fn=<NllLossBackward>)
tensor(2.1642, grad_fn=<NllLossBackward>)


In [30]:
predict_label=torch.argmax(model(pic.flatten(1)),dim=1)

In [32]:
print(predict_label)
print(label)

tensor([2, 0, 9, 2, 3, 2, 3, 7, 7, 7, 7, 3, 3, 0, 2, 3, 7, 7, 7, 4, 8, 3, 3, 1,
        1, 0, 0, 0, 8, 7, 6, 8, 6, 7, 9, 1, 4, 2, 5, 1, 1, 8, 6, 5, 7, 5, 4, 7,
        1, 4, 8, 4, 1, 8, 6, 8, 0, 7, 2, 2, 4, 3, 5, 0])
tensor([2, 0, 9, 2, 3, 2, 3, 9, 7, 7, 7, 3, 3, 0, 2, 3, 7, 7, 7, 4, 8, 3, 3, 1,
        1, 0, 0, 0, 8, 7, 6, 8, 6, 7, 9, 1, 4, 2, 5, 1, 1, 8, 6, 5, 7, 5, 4, 7,
        1, 4, 8, 4, 1, 8, 6, 8, 0, 7, 2, 2, 4, 3, 5, 0])


In [35]:
torch.mean((predict_label==label).float())

tensor(0.9844)