<a href="https://colab.research.google.com/github/profteachkids/CHE2064/blob/master/computational_methods/NeuralNetworkPrimer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torchvision as tv
from plotly.subplots import make_subplots

In [3]:
transforms=tv.transforms.Compose([tv.transforms.ToTensor()])
mnist=tv.datasets.MNIST('./', download=True, transform=transforms)

In [5]:
sampler = torch.utils.data.DataLoader(mnist, batch_size=64, shuffle=True)
data=iter(sampler)
a=next(data)

In [6]:
pic,label = a
print(pic.shape)
print(label.shape)
img=tv.utils.make_grid(pic, pad_value=255)
print(img.shape)

torch.Size([64, 1, 28, 28])
torch.Size([64])
torch.Size([3, 242, 242])


In [7]:
fig = make_subplots()
fig.add_image(z=img.permute([1,2,0])*255, colormodel='rgb')
fig.update_layout(width=500, height=500, margin=dict(l=2,r=2,b=2,t=2), xaxis_visible=False, yaxis_visible=False)

In [8]:
label.reshape(8,8)

tensor([[2, 0, 9, 2, 3, 2, 3, 9],
        [7, 7, 7, 3, 3, 0, 2, 3],
        [7, 7, 7, 4, 8, 3, 3, 1],
        [1, 0, 0, 0, 8, 7, 6, 8],
        [6, 7, 9, 1, 4, 2, 5, 1],
        [1, 8, 6, 5, 7, 5, 4, 7],
        [1, 4, 8, 4, 1, 8, 6, 8],
        [0, 7, 2, 2, 4, 3, 5, 0]])

In [26]:
model = nn.Sequential(nn.Linear(784,20),
                      nn.Tanh(),
                      nn.Linear(20,10),
                      nn.Softmax(dim=0))


In [27]:
loss_fn = nn.CrossEntropyLoss()
optim = torch.optim.Adam(model.parameters())

for i in range(1000):
  optim.zero_grad()
  predict=model(pic.flatten(1))
  loss = loss_fn(predict,label)
  if i % 100 == 0 :
    print(loss)
  loss.backward()
  optim.step()


tensor(2.3026, grad_fn=<NllLossBackward>)
tensor(2.1912, grad_fn=<NllLossBackward>)
tensor(2.1707, grad_fn=<NllLossBackward>)
tensor(2.1672, grad_fn=<NllLossBackward>)
tensor(2.1659, grad_fn=<NllLossBackward>)
tensor(2.1652, grad_fn=<NllLossBackward>)
tensor(2.1648, grad_fn=<NllLossBackward>)
tensor(2.1645, grad_fn=<NllLossBackward>)
tensor(2.1643, grad_fn=<NllLossBackward>)
tensor(2.1642, grad_fn=<NllLossBackward>)


In [30]:
predict_label=torch.argmax(model(pic.flatten(1)),dim=1)

In [32]:
print(predict_label)
print(label)

tensor([2, 0, 9, 2, 3, 2, 3, 7, 7, 7, 7, 3, 3, 0, 2, 3, 7, 7, 7, 4, 8, 3, 3, 1,
        1, 0, 0, 0, 8, 7, 6, 8, 6, 7, 9, 1, 4, 2, 5, 1, 1, 8, 6, 5, 7, 5, 4, 7,
        1, 4, 8, 4, 1, 8, 6, 8, 0, 7, 2, 2, 4, 3, 5, 0])
tensor([2, 0, 9, 2, 3, 2, 3, 9, 7, 7, 7, 3, 3, 0, 2, 3, 7, 7, 7, 4, 8, 3, 3, 1,
        1, 0, 0, 0, 8, 7, 6, 8, 6, 7, 9, 1, 4, 2, 5, 1, 1, 8, 6, 5, 7, 5, 4, 7,
        1, 4, 8, 4, 1, 8, 6, 8, 0, 7, 2, 2, 4, 3, 5, 0])


In [35]:
torch.mean((predict_label==label).float())

tensor(0.9844)